# Generated by Django 3.2.8 on 2021-10-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True)),
                ('atualizacao', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Nome',
                'verbose_name_plural': 'Nomes',
            },
        ),
    ]
