# Generated by Django 3.2.8 on 2021-10-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('profissao', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
            },
        ),
        migrations.DeleteModel(
            name='Nome',
        ),
    ]
