# Generated by Django 3.2.8 on 2021-10-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0003_atributos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atributos',
        ),
    ]
