# Generated by Django 3.2.8 on 2021-10-13 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0004_delete_atributos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modificadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('ataque', models.CharField(max_length=20)),
                ('velocidade', models.CharField(max_length=20)),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagens.profissao')),
            ],
            options={
                'verbose_name': 'Modificador de batalha',
                'verbose_name_plural': 'Modificadores de batalhas',
            },
        ),
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('pontos', models.IntegerField(verbose_name='Pontos de Vida: ')),
                ('forca', models.IntegerField(verbose_name='Força: ')),
                ('destreza', models.IntegerField(verbose_name='Destreza: ')),
                ('inteligencia', models.IntegerField(verbose_name='Inteligência: ')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagens.profissao')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
    ]
