# Generated by Django 3.2.8 on 2021-10-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0005_atributos_modificadores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modificadores',
            options={'verbose_name': 'Modificador de batalha', 'verbose_name_plural': 'Modificadores de batalha'},
        ),
        migrations.AlterField(
            model_name='atributos',
            name='destreza',
            field=models.IntegerField(verbose_name='Destreza'),
        ),
        migrations.AlterField(
            model_name='atributos',
            name='forca',
            field=models.IntegerField(verbose_name='Força'),
        ),
        migrations.AlterField(
            model_name='atributos',
            name='inteligencia',
            field=models.IntegerField(verbose_name='Inteligência'),
        ),
        migrations.AlterField(
            model_name='atributos',
            name='pontos',
            field=models.IntegerField(verbose_name='Pontos de Vida'),
        ),
        migrations.AlterField(
            model_name='modificadores',
            name='ataque',
            field=models.CharField(max_length=20, verbose_name='Ataque'),
        ),
        migrations.AlterField(
            model_name='modificadores',
            name='velocidade',
            field=models.CharField(max_length=20, verbose_name='Velocidade'),
        ),
        migrations.AlterField(
            model_name='profissao',
            name='profissao',
            field=models.CharField(max_length=15, verbose_name='Profissão'),
        ),
    ]
