# Generated by Django 3.2.8 on 2021-10-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0006_auto_20211013_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atributos',
            name='profissao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personagens.profissao'),
        ),
        migrations.AlterField(
            model_name='profissao',
            name='profissao',
            field=models.CharField(max_length=15, verbose_name='Profissões'),
        ),
    ]
