# Generated by Django 3.2.8 on 2021-10-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0007_auto_20211014_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificadores',
            name='profissao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personagens.profissao'),
        ),
    ]
