# Generated by Django 3.2.8 on 2021-10-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0008_alter_modificadores_profissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificadores',
            name='ataque',
            field=models.CharField(max_length=50, verbose_name='Ataque'),
        ),
        migrations.AlterField(
            model_name='modificadores',
            name='velocidade',
            field=models.CharField(max_length=50, verbose_name='Velocidade'),
        ),
    ]
