# Generated by Django 3.2.8 on 2021-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0009_auto_20211014_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modificadores',
            name='ataque',
            field=models.CharField(max_length=100, verbose_name='Ataque'),
        ),
        migrations.AlterField(
            model_name='modificadores',
            name='velocidade',
            field=models.CharField(max_length=100, verbose_name='Velocidade'),
        ),
    ]
