# Generated by Django 3.2.8 on 2021-11-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0010_auto_20211014_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nome',
                'verbose_name_plural': 'Nomes',
            },
        ),
        migrations.RenameModel(
            old_name='Profissao',
            new_name='Profissoes',
        ),
        migrations.RenameField(
            model_name='atributos',
            old_name='profissao',
            new_name='profissoes',
        ),
        migrations.RenameField(
            model_name='modificadores',
            old_name='profissao',
            new_name='profissoes',
        ),
        migrations.RenameField(
            model_name='profissoes',
            old_name='profissao',
            new_name='profissoes',
        ),
    ]
