# Generated by Django 3.2.8 on 2021-11-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0011_auto_20211101_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='nome',
            name='profissoes',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='personagens.profissoes'),
        ),
    ]
