# Generated by Django 3.2.8 on 2021-11-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0014_alter_nome_profissoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nome',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
    ]
