# Generated by Django 3.2.8 on 2021-11-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0015_alter_nome_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nome',
            name='nome',
            field=models.CharField(max_length=15, unique=True, verbose_name='Nome'),
        ),
    ]
