# Generated by Django 3.2.8 on 2021-11-03 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagens', '0016_alter_nome_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nome',
            new_name='Personagens',
        ),
    ]
